---
- hosts: all
  tasks:
    - name: Update all packages
      become: true
      apt:
        upgrade: dist
        update_cache: yes

    - name: update cache and install vim
      become: true
      apt:
        name: vim
        state: latest
        update_cache: yes

- hosts: backend
  vars_files:
    - config.yml
  roles:
    - docker
  tasks:
    - name: mysqldb
      become: true
      docker_container:
        name: mysqldb
        network_mode: bridge
        image: "{{ database_image }}"
        restart_policy: on-failure
        pull: true

    - name: airportdemo
      become: true
      docker_container:
        name: airportdemo
        network_mode: bridge
        image: "{{ server_image }}"
        restart_policy: on-failure
        ports:
          - "{{ server_port }}:{{ server_port }}"
        links:
          - "mysqldb:db"
        pull: true
        env:
            SPRING_DATASOURCE_URL: "{{ datasource_url }}"

- hosts: edge
  vars_files:
    - config.yml
  roles:
    - docker
  tasks:
    - include_role:
        name: proxy
      vars:
        image: "{{ proxy_image }}"
        upstream_port: "{{ server_port }}"
        upstream_ip: "172.17.177.22"
        port: "{{ external_port }}"