---
- hosts: all
  tasks:
    - name: Update all packages
      become: true
      apt:
        upgrade: dist
        update_cache: yes

    - name: update cache and install vim
      become: true
      apt:
        name: vim
        state: latest
        update_cache: yes

- hosts: backend
  roles:
    - docker
  tasks:
    - name: mysqldb
      become: true
      docker_container:
        name: mysqldb
        network_mode: bridge
        image: danielalarcao/airport-spring-boot-docker_mysql:latest
        restart_policy: on-failure
        pull: true

    - name: airportdemo
      become: true
      docker_container:
        name: airportdemo
        network_mode: bridge
        image: danielalarcao/airport-spring-boot-docker_webapp:latest
        restart_policy: on-failure
        ports:
          - "3000:3000"
        links:
          - "mysqldb:db"
        pull: true
        env:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lunatech?autoReconnect=true&useSSL=false&serverTimezone=UTC

- hosts: edge
  roles:
    - docker
    - proxy

